name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          IMAGE="europe-west1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/my-repo/my-image:${{ github.sha }}"
          
          docker build -t $IMAGE .
          docker push $IMAGE
